# Generated by Django 3.1.7 on 2021-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20210413_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Стихия')),
            ],
            options={
                'verbose_name': 'Стихия покемона',
                'verbose_name_plural': 'Стихии покемонов',
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='pokemon', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
    ]
