# Generated by Django 3.1.7 on 2021-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20210413_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(null=True, upload_to='element_types', verbose_name='Изображение'),
        ),
    ]
