# Generated by Django 3.1.7 on 2021-04-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, null=True, to='pokemon_entities.PokemonElementType', verbose_name='Силный против'),
        ),
    ]
